import type { Metadata } from "next";

import "./globals.css";
import { ReactNode } from "react";
import Header from "@/components/layout/Header";

import SyncUserWithConvex from "@/components/providers/SyncUserWithConvex";
import WrapperProvider from "@/components/providers/WrapperProvider";

export const metadata: Metadata = {
  title: "Ticket Clone",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="en">
      <body>
        <WrapperProvider>
          <Header />
          <SyncUserWithConvex />
          {children}
        </WrapperProvider>
      </body>
    </html>
  );
};
export default RootLayout;
